### PR TITLE
Added missing German translations

### PR DESCRIPTION
**Pull request by kosmas58**
1. Loaded and saved translations with BabelEdit
2. Added Bulgarian translation
3. Added missing German translations

### CODE REVIEW

**Comment by brunto** [comment]
@syl-p @kevin-atnos Could you do the review of this PR?

**Comment by brunto** [comment]
Hello @kosmas58 could you split your PR in multiple PR with fewer commits and fewer changed files?
It'll be easier to review.

**Comment by kevin-atnos** [comment]
Hello @kosmas58, thank you very much for your involvement and this PR!

Could you try splitting the work in this PR in different PR?

It is hard to review this whole PR as we have conflicts and lot's of different files updated.

Else, @syl-p we will need to review each commit and see what we have to report.

**Comment by kevin-atnos** [comment]
We added some changes manually, thank you.

**Pull request closed without merging**
